version: '3.9'
services:
  redis-master:
    image: 'redis:alpine'
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
  redis-slave:
    image: 'redis:alpine'
    ports:
      - '6379'
    depends_on: 
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=password
    command: redis-server --replicaof redis-master 6379
  web1:
    restart: on-failure
    build: ./web1
    ports:
      - '81:5000'
  web2:
    restart: on-failure
    build: ./web2
    ports:
      - '82:5000'
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web1
    - web2
